name: Train model

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
        name: dev 
    steps:
    - name: run pipeline
      run: az ml job create --file src/job.yml --resource-group az-ml-lab-sameer --workspace-name az-ml-ws-sameer
    - name: run
      run: az ml job create --file src/prod.yml --resource-group az-ml-lab-sameer --workspace-name az-ml-ws-sameer
