name: Manually trigger an Azure Machine Learning job

on: 
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Install Pytest
      run : pip install -U pytest
    - name: Install Pandas
      run : pip install pandas
    - name: Install Sklearn
      run: pip install sklearn
    - name: Install scikit-learn
      run: pip install -U scikit-learn
    - name: Install Mlflow
      run: pip install mlflow
    - name: Unit testing
      run: pytest tests/
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Run ML Job
      run: az ml job create --file src/job.yml --resource-group az-ml-lab-sameer --workspace-name az-ml-ws-sameer
      

