name: Environments

on: 
  workflow_dispatch:

jobs:
  dev:
    name: dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Run
      run: az ml job create --file src/dev.yml --resource-group az-ml-lab-sameer --workspace-name az-ml-ws-sameer

  
