---
name: Train model
on:
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: install az ml extension
        run: az extension add -n ml -y
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: run ml job
        run: az ml job create --file ./src/job.yml --resource-group az-ml-lab-sameer
          --workspace-name az-ml-ws-sameer --stream
      - name: run
        run: az ml job create --file ./workflows/prod.yml --resource-group az-ml-lab-sameer
          --workspace-name az-ml-ws-sameer --stream
